### ISSUE TITLE
UTMap bug

### ISSUE THREAD

**Issue by hiannie** [hiannie/CSC384-Project__Personalized-Course-Scheduler#18]
There is a bug generated when including the UTMap class when running the cost calculator. I am not sure how you would like to fix it. Not a big deal but of course it would be nice if you can fix it by Sunday.

**Comment by Bazhunga** [comment]
Could you copy paste the issue?

**Comment by hiannie** [comment]
Resolved. See the message on my commit 9:30 Apr. 2
